blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),
    path('tag/<slug:tag_slug>', views.post_list, name='post_list_by_tag'),
    # path('', views.PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',
         views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # namespace are unique across the entire project , 
    # can be used later to refer to blog urls
    # for eg, blog:post_list or blog:post_detail
    path('blog/', include('blog.urls', namespace='blog')),
]

blog/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User
from taggit.managers import TaggableManager
# Create your models here.

# custom model manager


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status='published')
        # Manager.get_queryset()


class Post(models.Model):
    STATUS_CHOICE = (
        # (actual value, humanreadable form)
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.CharField(max_length=250, unique_for_date='publish')
    # slug should remane unique for a specific date, but can otherwise vary
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(
        max_length=10, choices=STATUS_CHOICE, default='draft')
    objects = models.Manager()  # default manager
    # if we have created a custom manager but also want to use the default
    # manager than we have to explicitly declare it
    published = PublishedManager()  # custom manager
    tags = TaggableManager()

    class Meta:
        # for ordering in descending order
        ordering = ('-publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail',
                       args=[self.publish.year,
                             self.publish.month,
                             self.publish.day, self.slug])


class Comment(models.Model):
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return f"Comment by {self.name} on {self.post}"

blog/forms.py
from django import forms
from .models import Comment
class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views.generic import ListView
from django.core.mail import send_mail
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Count
from taggit.models import Tag
from .forms import EmailPostForm, CommentForm
from .models import Post, Comment
from django.db.models import Count

# class PostListView(ListView):
#     queryset = Post.published.all()  # (instead) model = Post
#     context_object_name = 'posts'  # dflt: object_list
#     paginate_by = 3
#     template_name = 'blog/post/list.html'  # dflt: blog/post_list.html


def post_list(request, tag_slug=None):
    '''
        here this is function based view of the post-list-view
    '''
    object_list = Post.published.all()  # custom manager
    tag = None

    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 3)  # 3 post in one page
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)
    return render(request, 'blog/post/list.html', {'page': page, 'posts': posts, 'tag': tag})


def post_detail(request, year, month, day, post):
    # if the particular object is not found it shows 404 error
    post = get_object_or_404(Post, slug=post,
                             status='published',
                             publish__year=year,
                             publish__month=month,
                             publish__day=day)
    # List of active active comments
    comments = post.comments.filter(active=True)

    new_comment = None

    if request.method == 'POST':
        # a commmet was posted
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create comment but don't save to database yet
            # new Comment object is created by calling form's save method
            # the save method creates an instance of the model that the form is linked to and save it to the database, but in commit=false only model instance is created but not saved
            new_comment = comment_form.save(commit=False)
            # Assign the current post to comment
            new_comment.post = post
            # now save the comment to database
            new_comment.save()
    else:
        comment_form = CommentForm()

    # List of similar post
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids)\
        .exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags'))\
        .order_by('-same_tags', '-publish')[:4]
    return render(request, 'blog/post/detail.html', {'post': post, 'comments': comments, 'new_comment': new_comment, 'comment_form': comment_form, 'similar_posts': similar_posts})


def post_share(request, post_id):
    # Retrieve post by id
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False

    if request.method == 'POST':
        # form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data  # form fields passed validation
            post_url = request.build_absolute_uri(post.get_absolute_url())
            # _...uri builds a complete URL(http schema & hostname)
            subject = f"{cd['name']} recommends you read " \
                      f"{post.title}"
            message = f"Read {post.title} at {post_url}\n\n" \
                      f"{cd['name']}'s comments: {cd['comments']}"
            send_mail(subject, message,
                      'testerperson1029@gmail.com', [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post, 'form': form, 'sent': sent})

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>

<head>
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
        integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link href="{% static 'css/blog.css' %}" rel="stylesheet">
</head>

<body>
    <div class="container">
        {% block content %}r
        {% endblock %}
    </div>
    <!-- <div id="sidebar">
        <h2>My Blog</h2>
        <p>This is my blog.</p>
    </div> -->
</body>

</html>

blog/templates/blog/pagination.html
<div class="pagination">
  <span class="steps-links">
    {% if page.has_previous %}
    <a href="?page={{ page.previous_page_number }}">Previous</a>
    {% endif %}
    <span class="current">
      Page {{ page.number }} of {{ page.paginator.num_pages }}
    </span>
    {% if page.has_next %}
    <a href="?page={{ page.next_page_number }}">Next</a>
    {% endif %}
  </span>
</div>

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}

{% block title %}
{{ post.title }}
{% endblock %}
{% block content %}
<h1>{{ post.title }}</h1>
<p class="date">
    Published {{ post.publish }} by {{ post.author }}
</p>
{{ post.body|linebreaks }}
<p>
    <a href="{% url 'blog:post_share' post.id %}">
        Share this post
    </a>
</p>
<h2>Similar posts</h2>
{% for post in similar_posts %}
<p>
    <a href="{{ post.get_absolute_url }}">
        {{ post.title }}
    </a>
</p>
{% empty %}
There are no similar posts yet.
{% endfor %}
{% with comments.count as total_comments %}
<h2>
    {{ total_comments }} comment{{ total_comments|pluralize }}
</h2>
{% endwith %}

{% for comment in comments %}
<div class="comment">
    <p class="info">
        Comment {{ forloop.counter }} by {{ comment.name }}
    </p>
    {{ comment.body|linebreaks }}
</div>
{% empty %}
<p>There is no comments yet</p>
{% endfor %}

{% if new_comment %}
<h2>Your comment has been added.</h2>
{% else %}
<h2>Add a new comment</h2>
<form action="" method="post">
    {{ comment_form.as_p }}
    {% csrf_token %}
    <p><input type="submit" value="Add comment"></p>
</form>
{% endif %}
{% endblock %}

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}

{% block title %}My Blog{% endblock %}
{% block content %}
<div class='row d-flex justify-content-center'>
    <h1>My Blog</h1>
    <div class="col-12 text-center">
        {% if tag %}
        <h2>Posts tagged with "{{ tag.name }}"</h2>
        {% endif %}
    </div>
    {% for post in posts %}
    <div class="col-12 mt-3 d-flex justify-content-center">
        <div class="card" style="width: 39rem;">
            <div class="card-header">
                <a href="{{ post.get_absolute_url }}">
                    {{ post.title }}
                </a>
                <p class="tags">
                    Tags:
                    {% for tag in post.tags.all %}
                    <a href="{% url 'blog:post_list_by_tag' tag.slug %}">
                        {{ tag.name }}
                    </a>
                    {% if not forloop.last %}, {% endif %}
                    {% endfor %}
                </p>
            </div>
            <div class="card-body">
                <div class="card-text">
                    <p class='date'>
                        Published {{ post.publish }} by {{ post.author }}
                    </p>
                    {{ post.body|truncatewords:30|linebreaks }}
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    {% include "blog/pagination.html" with page=posts %}

</div>

{% endblock %}

blog/templates/blog/post/share.html
{% extends "blog/base.html" %}
{% block title %}Share a post{% endblock %}

{% block content %}
{% if sent %}
<h1>E-mail Successfully send</h1>
<p>
    "{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.
</p>
{% else %}
<h1>Share "{{ post.title }}" by e-mail</h1>
<form action="" method="post"> {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Send e-mail">
</form>
{% endif %}
{% endblock %}